using HarmonyLib;
using Kingmaker;
using Kingmaker.Blueprints;
using Kingmaker.Blueprints.JsonSystem;
using Kingmaker.Blueprints.Root;
using Kingmaker.Localization;
using Kingmaker.Sound;
using Kingmaker.Visual.Sound;
using System.Reflection;
using UnityEngine;
using UnityModManagerNet;

namespace {SourceName};

public static class Main {
    internal static Harmony HarmonyInstance;
    internal static UnityModManager.ModEntry.ModLogger Log;

    public static bool Load(UnityModManager.ModEntry modEntry) {
        Log = modEntry.Logger;
        modEntry.OnGUI = OnGUI;
        HarmonyInstance = new Harmony(modEntry.Info.Id);
        try {
            HarmonyInstance = new Harmony(modEntry.Info.Id);
        } catch {
            HarmonyInstance.UnpatchAll(HarmonyInstance.Id);
            throw;
        }
        return true;
    }

    public static void OnGUI(UnityModManager.ModEntry modEntry) {

    }

    [HarmonyPatch]
    public static class Soundbanks {
        // Adds the mod's folder to the soundbank search paths so that the game knows where to look when trying
        // to load any of the included soundbanks.
        [HarmonyPatch(typeof(AkAudioService), nameof(AkAudioService.Initialize))]
        [HarmonyPostfix]
        public static void AddBankPaths()
        {
            var banksPath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            AkSoundEngine.AddBasePath(banksPath);
        }

        // Must match the name of your character creator preview Event, i.e PreviewSound in the blueprint.
        const string PreviewName = "{SourceName}_Test";
        static readonly uint PreviewEventId = AkSoundEngine.GetIDFromString(PreviewName);

        // Patches the call to play a preview sound in the character creator's voice selection window.
        // If the added soundset is selected, the bank is loaded into memory if it isn't already.
        [HarmonyPatch(typeof(UnitAsksComponent), nameof(UnitAsksComponent.PlayPreview))]
        [HarmonyPrefix]
        static bool LoadPreviewBank(UnitAsksComponent __instance)
        {
            // If the selected preview is not the mod's, return the original method.
            if (__instance.PreviewSound is not PreviewName)
                return true;

            // If it is the mod's make sure the preview bank is loaded.
            if (!SoundBanksManager.s_Handles.Any(handle => handle.Key is PreviewName))
                SoundBanksManager.LoadBankSync(PreviewName);

            // Pass the event to the PostEvent handler.
            GameObject gameObject = Game.Instance.UI.Common.gameObject;
            SoundEventsManager.PostEvent(PreviewEventId, gameObject);

            return false;
        }

        [HarmonyPatch(typeof(BlueprintsCache), nameof(BlueprintsCache.Init))]
        [HarmonyPostfix]
        static void AddAsksListBlueprint()
        {
            LocalizationManager.CurrentPack.PutString("{SourceName}", "{Description}");

            var blueprint = new BlueprintUnitAsksList
            {
                // Every mod requires its own unique GUID. Autogenerated on template creation.
                AssetGuid = new(System.Guid.Parse("{ModGUID}")),
                name = "{SourceName}_Barks",
                DisplayName = new() { m_Key = "{SourceName}" }
            };

            blueprint.ComponentsArray =
            [
                new UnitAsksComponent()
            {
                OwnerBlueprint = blueprint,

                // Change this to match the name of your primary soundbank.
                SoundBanks = [ "{SourceName}_GVR_ENG" ],
                // This is the name of your character creator preview sounds Event. Make sure
                // that it matches the name of the Event in your Wwise project.
                PreviewSound = "{SourceName}_Test",
                Aggro = new()
                {
                    Entries =
                    [
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_CombatStart_01",
                            RandomWeight = 0.0f,
                            ExcludeTime = 2,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_CombatStart_02",
                            RandomWeight = 0.0f,
                            ExcludeTime = 2,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_CombatStart_03",
                            RandomWeight = 0.0f,
                            ExcludeTime = 2,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        }
                    ],
                    Cooldown = 0.0f,
                    InterruptOthers = true,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 1.0f,
                    ShowOnScreen = false
                },
                Pain = new()
                {
                    Entries =
                    [
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Pain",
                            RandomWeight = 0.0f,
                            ExcludeTime = 0,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        }
                    ],
                    Cooldown = 2.0f,
                    InterruptOthers = false,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 1.0f,
                    ShowOnScreen = false
                },
                Fatigue = new()
                {
                    Entries =
                    [
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Fatigue",
                            RandomWeight = 0.0f,
                            ExcludeTime = 0,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        }
                    ],
                    Cooldown = 60.0f,
                    InterruptOthers = false,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 1.0f,
                    ShowOnScreen = false
                },
                Death = new()
                {
                    Entries =
                    [
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Death",
                            RandomWeight = 0.0f,
                            ExcludeTime = 0,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        }
                    ],
                    Cooldown = 0.0f,
                    InterruptOthers = true,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 1.0f,
                    ShowOnScreen = false
                },
                Unconscious = new()
                {
                    Entries =
                    [
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Unconscious",
                            RandomWeight = 0.0f,
                            ExcludeTime = 0,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        }
                    ],
                    Cooldown = 0.0f,
                    InterruptOthers = true,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 1.0f,
                    ShowOnScreen = false
                },
                LowHealth = new()
                {
                    Entries =
                    [
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_LowHealth_01",
                            RandomWeight = 0.0f,
                            ExcludeTime = 1,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_LowHealth_02",
                            RandomWeight = 0.0f,
                            ExcludeTime = 1,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        }
                    ],
                    Cooldown = 10.0f,
                    InterruptOthers = false,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 1.0f,
                    ShowOnScreen = false
                },
                CriticalHit = new()
                {
                    Entries =
                    [
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_CharCrit_01",
                            RandomWeight = 0.0f,
                            ExcludeTime = 2,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_CharCrit_02",
                            RandomWeight = 0.0f,
                            ExcludeTime = 2,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_CharCrit_03",
                            RandomWeight = 0.0f,
                            ExcludeTime = 2,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        }
                    ],
                    Cooldown = 0.0f,
                    InterruptOthers = false,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 0.7f,
                    ShowOnScreen = false
                },
                Order = new()
                {
                    Entries =
                    [
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_AttackOrder_01",
                            RandomWeight = 0.0f,
                            ExcludeTime = 3,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_AttackOrder_02",
                            RandomWeight = 0.0f,
                            ExcludeTime = 3,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_AttackOrder_03",
                            RandomWeight = 0.0f,
                            ExcludeTime = 3,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_AttackOrder_04",
                            RandomWeight = 0.0f,
                            ExcludeTime = 3,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        }
                    ],
                    Cooldown = 0.0f,
                    InterruptOthers = false,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 1.0f,
                    ShowOnScreen = false
                },
                OrderMove = new()
                {
                    Entries =
                    [
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Move_01",
                            RandomWeight = 0.0f,
                            ExcludeTime = 4,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Move_02",
                            RandomWeight = 0.0f,
                            ExcludeTime = 4,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Move_03",
                            RandomWeight = 0.0f,
                            ExcludeTime = 4,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Move_04",
                            RandomWeight = 0.0f,
                            ExcludeTime = 4,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Move_05",
                            RandomWeight = 0.0f,
                            ExcludeTime = 4,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Move_06",
                            RandomWeight = 0.0f,
                            ExcludeTime = 2,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Move_07",
                            RandomWeight = 0.0f,
                            ExcludeTime = 4,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        }
                    ],
                    Cooldown = 10.0f,
                    InterruptOthers = false,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 0.1f,
                    ShowOnScreen = false
                },
                Selected = new()
                {
                    Entries =
                    [
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Select_01",
                            RandomWeight = 1.0f,
                            ExcludeTime = 4,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Select_02",
                            RandomWeight = 1.0f,
                            ExcludeTime = 4,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Select_03",
                            RandomWeight = 1.0f,
                            ExcludeTime = 4,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Select_04",
                            RandomWeight = 1.0f,
                            ExcludeTime = 4,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Select_05",
                            RandomWeight = 1.0f,
                            ExcludeTime = 4,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Select_06",
                            RandomWeight = 1.0f,
                            ExcludeTime = 4,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_SelectJoke",
                            RandomWeight = 0.1f,
                            ExcludeTime = 30,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        }
                    ],
                    Cooldown = 0.0f,
                    InterruptOthers = false,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 1.0f,
                    ShowOnScreen = false
                },
                RefuseEquip = new()
                {
                    Entries =
                    [
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_CantEquip_01",
                            RandomWeight = 1.0f,
                            ExcludeTime = 2,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_CantEquip_02",
                            RandomWeight = 1.0f,
                            ExcludeTime = 2,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        }
                    ],
                    Cooldown = 0.0f,
                    InterruptOthers = true,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 1.0f,
                    ShowOnScreen = false
                },
                RefuseCast = new()
                {
                    Entries =
                    [
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_CantCast",
                            RandomWeight = 0.0f,
                            ExcludeTime = 1,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        }
                    ],
                    Cooldown = 0.0f,
                    InterruptOthers = true,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 1.0f,
                    ShowOnScreen = false
                },
                CheckSuccess = new()
                {
                    Entries =
                    [
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_CheckSuccess_01",
                            RandomWeight = 1.0f,
                            ExcludeTime = 2,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_CheckSuccess_02",
                            RandomWeight = 1.0f,
                            ExcludeTime = 2,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        }
                    ],
                    Cooldown = 0.0f,
                    InterruptOthers = false,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 1.0f,
                    ShowOnScreen = false
                },
                CheckFail = new()
                {
                    Entries =
                    [
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_CheckFail_01",
                            RandomWeight = 1.0f,
                            ExcludeTime = 2,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_CheckFail_02",
                            RandomWeight = 1.0f,
                            ExcludeTime = 2,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        }
                    ],
                    Cooldown = 0.0f,
                    InterruptOthers = false,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 1.0f,
                    ShowOnScreen = false
                },
                RefuseUnequip = new()
                {
                    Entries = [],
                    Cooldown = 0.0f,
                    InterruptOthers = false,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 1.0f,
                    ShowOnScreen = false
                },
                Discovery = new()
                {
                    Entries =
                    [
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Discovery_01",
                            RandomWeight = 0.0f,
                            ExcludeTime = 1,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        },
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_Discovery_02",
                            RandomWeight = 0.0f,
                            ExcludeTime = 1,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        }
                    ],
                    Cooldown = 0.0f,
                    InterruptOthers = false,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 1.0f,
                    ShowOnScreen = false
                },
                Stealth = new()
                {
                    Entries =
                    [
                        new()
                        {
                            Text = null,
                            AkEvent = "{SourceName}_StealthMode",
                            RandomWeight = 1.0f,
                            ExcludeTime = 1,
                            m_RequiredFlags = [],
                            m_ExcludedFlags = [],
                            m_RequiredEtudes = null,
                            m_ExcludedEtudes = null
                        }
                    ],
                    Cooldown = 0.0f,
                    InterruptOthers = false,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 1.0f,
                    ShowOnScreen = false
                },
                StormRain = new()
                {
                    Entries = [],
                    Cooldown = 0.0f,
                    InterruptOthers = false,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 1.0f,
                    ShowOnScreen = false
                },
                StormSnow = new()
                {
                    Entries = [],
                    Cooldown = 0.0f,
                    InterruptOthers = false,
                    DelayMin = 0.0f,
                    DelayMax = 0.0f,
                    Chance = 1.0f,
                    ShowOnScreen = false
                },
                AnimationBarks =
                [
                    new()
                    {
                        Entries =
                        [
                            new()
                            {
                                Text = null,
                                AkEvent = "{SourceName}_AttackShort",
                                RandomWeight = 0.0f,
                                ExcludeTime = 0,
                                m_RequiredFlags = [],
                                m_ExcludedFlags = [],
                                m_RequiredEtudes = null,
                                m_ExcludedEtudes = null
                            }
                        ],
                        Cooldown = 0.0f,
                        InterruptOthers = false,
                        DelayMin = 0.0f,
                        DelayMax = 0.0f,
                        Chance = 0.7f,
                        ShowOnScreen = false,
                        AnimationEvent = MappedAnimationEventType.AttackShort
                    },
                    new()
                    {
                        Entries =
                        [
                            new()
                            {
                                Text = null,
                                AkEvent = "{SourceName}_CoupDeGrace",
                                RandomWeight = 0.0f,
                                ExcludeTime = 0,
                                m_RequiredFlags = [],
                                m_ExcludedFlags = [],
                                m_RequiredEtudes = null,
                                m_ExcludedEtudes = null
                            }
                        ],
                        Cooldown = 0.0f,
                        InterruptOthers = true,
                        DelayMin = 0.0f,
                        DelayMax = 0.0f,
                        Chance = 1.0f,
                        ShowOnScreen = false,
                        AnimationEvent = MappedAnimationEventType.CoupDeGrace
                    },
                    new()
                    {
                        Entries = [],
                        Cooldown = 0.0f,
                        InterruptOthers = true,
                        DelayMin = 0.0f,
                        DelayMax = 0.0f,
                        Chance = 1.0f,
                        ShowOnScreen = false,
                        AnimationEvent = MappedAnimationEventType.Cast
                    },
                    new()
                    {
                        Entries = [],
                        Cooldown = 0.0f,
                        InterruptOthers = true,
                        DelayMin = 0.0f,
                        DelayMax = 0.0f,
                        Chance = 1.0f,
                        ShowOnScreen = false,
                        AnimationEvent = MappedAnimationEventType.CastDirect
                    },
                    new()
                    {
                        Entries = [],
                        Cooldown = 0.0f,
                        InterruptOthers = true,
                        DelayMin = 0.0f,
                        DelayMax = 0.0f,
                        Chance = 1.0f,
                        ShowOnScreen = false,
                        AnimationEvent = MappedAnimationEventType.CastLong
                    },
                    new()
                    {
                        Entries = [],
                        Cooldown = 0.0f,
                        InterruptOthers = true,
                        DelayMin = 0.0f,
                        DelayMax = 0.0f,
                        Chance = 1.0f,
                        ShowOnScreen = false,
                        AnimationEvent = MappedAnimationEventType.CastShort
                    },
                    new()
                    {
                        Entries = [],
                        Cooldown = 0.0f,
                        InterruptOthers = true,
                        DelayMin = 0.0f,
                        DelayMax = 0.0f,
                        Chance = 1.0f,
                        ShowOnScreen = false,
                        AnimationEvent = MappedAnimationEventType.CastTouch
                    },
                    new()
                    {
                        Entries = [],
                        Cooldown = 0.0f,
                        InterruptOthers = true,
                        DelayMin = 0.0f,
                        DelayMax = 0.0f,
                        Chance = 1.0f,
                        ShowOnScreen = false,
                        AnimationEvent = MappedAnimationEventType.CastYourself
                    },
                    new()
                    {
                        Entries = [],
                        Cooldown = 0.0f,
                        InterruptOthers = true,
                        DelayMin = 0.0f,
                        DelayMax = 0.0f,
                        Chance = 1.0f,
                        ShowOnScreen = false,
                        AnimationEvent = MappedAnimationEventType.Omnicast
                    },
                    new()
                    {
                        Entries = [],
                        Cooldown = 0.0f,
                        InterruptOthers = true,
                        DelayMin = 0.0f,
                        DelayMax = 0.0f,
                        Chance = 1.0f,
                        ShowOnScreen = false,
                        AnimationEvent = MappedAnimationEventType.Precast
                    },
                ],
            },
            ];

                ResourcesLibrary.BlueprintsCache.AddCachedBlueprint(blueprint.AssetGuid, blueprint);

                BlueprintRoot.Instance.CharGen.m_MaleVoices = BlueprintRoot.Instance.CharGen.m_MaleVoices
                    .Append(blueprint.ToReference<BlueprintUnitAsksListReference>())
                    .ToArray();
        }
    }
}
